### ISSUE TITLE
Default value of VME_LOG_LEVEL

### ISSUE THREAD

**Issue by Grandma-Betty** [awkspace/vmm-export#1]
It's not really an issue but the default value of _VME_LOG_LEVEL_ is not **WARNING** as described in your readme.md, it is **INFO**.

**Comment by awkspace** [comment]
Fixed in b2f0f4e. The default log level was `WARNING` in the cli and `INFO` in the container. I set them both to `INFO`.

**Comment by Grandma-Betty** [comment]
You did not update the docker image yet ;-)
Thanks!
