### ISSUE TITLE
Path of the created image by QEMU on Synology

### ISSUE THREAD

**Issue by FloatingLizard** [awkspace/vmm-export#2]
Hello, 

  I am not sure if this is the correct area for this question.  Looking at your solution and I wish I knew about it.

  I need to find the VDI image created by the Synolgy Virtual Machine location to see if I can restore it.  

Thank you.

**Comment by awkspace** [comment]
You can use `VME_PATH` to determine where the VDI images are saved. It takes the form `/[Volume Name]/[Folder Name]`. `vmm-export` has no default value for this variable and will not run unless you set it.

**Comment by FloatingLizard** [comment]
Actually I am sorry I was not clear.  I was wondering about the source of where the path of the export was on the Synology. 
I am trying to restore image that was created.
