### ISSUE TITLE
Problems getting vmm-export up and running

### ISSUE THREAD

**Issue by YouDoMeIDoYou** [awkspace/vmm-export#3]
Hi there, thanks for providing a vmm backup-solution for my synology! But it doesn't work for me so far ... I'm not sure, if I followed your installation correctly, so here a steb-by-step list:

DS1817+, DSM 7.0-41890
Virtual Machine Manager 2.5.5-11487 -> Windows 10 Pro Installation
Docker 20.10.3-1239

- Created a new admin named "vmm-export"
- Docker -> Image -> Add from URL -> https://hub.docker.com/r/awkspace/vmm-export -> Downloading (78MB)
- Click on "awkspace/vmm-export:latest" in "Image" and "Launch"
CREATE CONTAINER
- Advanced Settings - Enable auto-start <- check
- Volume - leave it
- Network - leave at "bridge"
- Port Settings - leave it
- Links - leave
- ENVIRONMENT
- VME_USERNAME -> vmm-export
- VME_PASSWORD -> password of user "vmm-export"
- VME_DSM_URL -> 192.168.188.100:5000
- VME_PATH -> /volume1/vmm-export
- VME_CRON -> 0 0/5 0 ? * * * (every five minutes for testing - don't know how to trigger vmm-export manually)
- VME_WORKERS -> 1
- VME_LOG_LEVEL -> INFO (leave)
- PATH -> /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin (leave)
- -> finish, "Run this container after the wizard has finished" <- check
CHECK STATUS
- in "Container" I select the container "awkspace-vmm-export" (Running) and click on "Details"
- under "Log" I see:
Time            Log                                                                                 Stream
14:15:49      crond[8]: crond (busybox 1.33.1) started, log level 8        stdout
14:15:49      crond[8]: user root: parse error at ?                                 stdout
14:16:00      crond[8]: user root: parse error at ?                                 stdout

Nothing else is happening, what did I miss?

**Comment by awkspace** [comment]
`crond` is complaining that your cron expression is invalid. `busybox`'s `crond` (the one used in Alpine containers) doesn't understand `?`. Also, there's no 0th day of the month.

Try `*/5 * * * *` if you want it to run every five minutes, and use https://crontab.guru/ to check cron expressions. I'll update the README to point to that site as well.

**Comment by YouDoMeIDoYou** [comment]
Thanks for your reply. I changed my cron expression to */5 * * * *
Now I get the following output:
crond[7]: crond (busybox 1.33.1) started, log level 8
crond[7]: USER root pid   8 cmd /usr/bin/vmm-export
INFO:vmm_export:Retrieving list of VMs...
INFO:vmm_export:[vm-windows] Deleting old export, if it exists...
ERROR:vmm_export:Full response from DSM: {"error": {"code": 900, "errors": [{"code": 408, "path": "/volume1/vmm-export/vm-windows.ova"}]}, "success": false}
crond[7]: user root: process already running: /usr/bin/vmm-export

Do I have to give your container access to /volume1/vmm-export via Docker volume settings?

**Comment by awkspace** [comment]
You're giving it the OS path, not the shared folder path. If a shared folder called `vmm-export` exists (check Shared Folder in Control Panel), then the correct path would be `/vmm-export`. Note that you can tell it to export to a subdirectory in a shared folder too, for example `/MyShareName/VMM`.

**Comment by YouDoMeIDoYou** [comment]
Thanks for your feedback! I fixed the path for the shared folder and the backup-process is working fine now :) The only thing missing is even when I give a TZ variable (Europe/Vienna) the backup is running at time but the log represents the "wrong" time. Is it possible to define the number of saved .ova-backups before they get overwritten?

**Comment by awkspace** [comment]
The fact that the Docker logs are still in UTC is a quirk of the DSM interface. I haven't found a way to get them to display in anything other than UTC.
As for the number of saved backups, this tool is meant to work with with Hyper Backup or another DSM application that picks up the ova files and handles the versioning. Hyper Backup already has flexible options for file version lifecycles so I didn't feel the need to duplicate that.
Since the tool appears to be working for you now I'm going to close this ticket. Please open another one if you run into any other difficulties.

**Comment by tom9865** [comment]
Had the same path issue.
Now path seems to be fixed but I am getting:

ERROR: vmm_export:Task failed with error code 931
ERROR: vmm_export:Failed exporting VM_.
INFO: vmm_export:[VM_] Export finished
INFO: vmm_export:[VM_] Waiting for export to finish..

Any ideas?

br, Tom
