### ISSUE TITLE
snapshot without shutting down

### ISSUE THREAD

**Issue by RobMeerwijk** [awkspace/vmm-export#4]
Hi I have been looking for a solution for automated exports. I tried yours, maybe you could implement this option:

/var/packages/Virtualization/target/bin/vmm_backup_ova 

This command line utility creates a temp stopped vm from a snapshot and then exports the temp vm.

**Comment by awkspace** [comment]
This operates over the Synology API. The local scripts have full access to `qemu-kvm` and operate differently. Is there an API call that would perform this function?

**Comment by RobMeerwijk** [comment]
I would not know. I have just scheduled a cronjob using vmm_backup_ova. Works like a breeze

**Comment by NoTheo** [comment]
> I would not know. I have just scheduled a cronjob using vmm_backup_ova. Works like a breeze

Rob, can you share your cronjob? Much appreciated.

**Comment by awkspace** [comment]
Closing as local script access is outside the scope of a container-based solution.

**Comment by RobMeerwijk** [comment]
Of course, but it is actually really straightforward

#backup vm's
0       1       *       *       *       root 
/var/packages/Virtualization/target/bin/vmm_backup_ova --dst=backup 
 >/dev/null 2>&1

Make sure you have a share called backup. You can also usa a different 
share.

Op 6-2-2022 om 14:08 schreef NoTheo:

**Comment by tom9865** [comment]
Hello, 
as I am getting frustrated, I thought I'll give it a try ro share my status and ask for advice...

- Script is working
- Cloning of VM working
- Exporting of cloned VM working
- Delete cloned VM working

But after the script finished, there is no OVA file on the backup share.

Any idea what could be wrong?

br,
Tom
